# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'S-Life' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Alamofire'
	pod 'AlamofireObjectMapper', '~> 5.2'
	pod 'Mapbox-iOS-SDK', '~> 6.3.0'
  # Pods for S-Life

end
